set_away_date_range:
  fields:
    config_entry:
      required: True
      selector:
        config_entry:
          integration: keba_keenergy
    start_date:
      example: 2026-01-01
      required: True
      selector:
        date:
    end_date:
      example: 2026-01-14
      required: True
      selector:
        date:

set_heating_curve_points:
  fields:
    config_entry:
      required: True
      selector:
        config_entry:
          integration: keba_keenergy
    heating_curve:
      example: hc1
      required: True
      selector:
        select:
          options:
            - HC1
            - HC2
            - HC3
            - HC4
            - HC5
            - HC6
            - HC7
            - HC8
            - HC_FBH
            - HC_HK
          translation_key: heating_curve
    points:
      example:
        - outdoor: 20
          flow: 20
        - outdoor: 0
          flow: 30
        - outdoor: -20
          flow: 40
      required: True
      selector:
        object:
