name: Security

permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
  schedule:
    - cron: 30 5 * * *

jobs:
  security:
    name: Audit packages
    runs-on: ubuntu-latest
    continue-on-error: True
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Create requirements.txt
        run: uv export --quiet --locked --all-extras --dev --no-hashes --no-editable --output-file=requirements.txt
      - name: Audit python packages
        run: uv run pip-audit --requirement=requirements.txt
